baseURL: ""
languageCode: en-us
title: JFREV
theme: PaperMod

params:
  homeInfoParams:
    Title: Welcome Stranger
    Content: i am not on any lists, i do not have any trophies. I am just grateful for my opportunities
   
  ShowBreadCrumbs: true
  ShowPostNavLinks: true

menu:
    main:
    - identifer: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifer: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifer: archives
      name: Archives
      url: /archives/
      weight: 30